#! /usr/bin/env python3
import sys
import click
from tabulate import tabulate
from ofcourse import dumpers
from ofcourse import parsers

@click.group()
def cli():
    pass


@cli.group("people")
def people_group():
    pass


@cli.group("course")
def course_group():
    pass


@people_group.command("normalize")
@click.argument("filename", default="./people.yml", type=click.Path(exists=True, dir_okay=False, writable=True))
def people_normalize(filename):
    with open(filename, 'r') as f:
        person_list = parsers.person_list_parser(f)
    if not person_list:
        exit()
    with open(filename, 'w') as f:
        dumpers.person_list_yaml_dumper(f, person_list)


@course_group.command("print")
@click.argument("filename", type=click.Path(exists=True, dir_okay=False))
@click.argument("people-file", default="./people.yml", type=click.Path(exists=True, dir_okay=False))
def course_print(filename, people_file):
    with open(people_file, 'r') as f:
        person_list = parsers.person_list_parser(f)
    with open(filename, 'r') as f:
        course = parsers.course_parser(f, person_list)
    dumpers.course_text_dumper(sys.stdout, course)


if __name__ == '__main__':
    cli()
